### ISSUE TITLE
英語表示時にも title タグのテキストが日本語になっている

### ISSUE THREAD

**Issue by inutano** [dbcls/togotv#4]
https://togotv.dbcls.jp/en で `<title>` が `トップ | 統合TV` になっていますね。`welcome.html` `ajacs_text.html` も同様です。以下提案。

- Top https://togotv.dbcls.jp/en
- Welcome to TogoTV! https://togotv.dbcls.jp/en/welcome.html
- Trainings https://togotv.dbcls.jp/en/ajacs_text.html?page=1

**Comment by reika0717** [comment]
@hiromasaono @inutano こちら対応致しました。
日本語のみのコンテンツ（スキルセットや講習会資料）以外のページは英語のタイトルになるように修正しております。ご確認お願いします。

**Comment by inutano** [comment]
問題ないとおもいます！早速のご対応ありがとうございます！！
