### ISSUE TITLE
「講習会資料を探す」のページの title が「テキスト検索」になっている

### ISSUE THREAD

**Issue by inutano** [dbcls/togotv#5]
何をテキスト検索するんですか的な混乱を招くので title も `講習会資料を探す` にするとよいのではないでしょうか！

**Comment by reika0717** [comment]
こちらはシンプルな間違いでした…ご指摘有難うございます！
修正しております。
http://localhost:3000/ajacs_text.html

**Comment by reika0717** [comment]
@hiromasaono @inutano こちらはシンプルに間違えてました…ご指摘有難うございます！
修正しております。
https://togotv.dbcls.jp/ajacs_text.html

**Comment by inutano** [comment]
ありがとうございます！！！！！！！！！！！！！
