### ISSUE TITLE
検索結果のURLをダイレクトで叩くと、「Undefined」の検索結果　になる

### ISSUE THREAD

**Issue by hiromasaono** [dbcls/togotv#6]
例:　https://togotv.dbcls.jp/result.html?type=%E5%8B%95%E7%94%BB%E3%83%9E%E3%83%8B%E3%83%A5%E3%82%A2%E3%83%AB&page=1&query=BLAST

**Comment by reika0717** [comment]
@hiromasaono こちら対応致しました。ご確認お願い致します。
